# Generated by Django 2.0.6 on 2018-06-23 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20180623_1318'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='my_user',
            new_name='user',
        ),
    ]
